version: '3.8'
services:
  application:
    build: .
    container_name: application
    env_file: "./.env"
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    depends_on:
      - database
      - migrations
    networks:
      - backend

  database:
    image: 'postgres:16'
    container_name: db-postgres
    env_file: "./.env"
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend

  migrations:
    image: liquibase/liquibase:4.26
    container_name: liquibase-migrations
    env_file: "./.env"
    depends_on:
      - database
    command:
      - --changelog-file=changelog-main.yml
      - --search-path=/liquibase/changelog/
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://db-postgres:5432/${DB_NAME}
      - --username=${DB_USERNAME}
      - --password=${DB_PASSWORD}
      - update
#      - update-to-tag
#      - version_2
#      - rollback
#      - version_1
#      - update-count
#      - --count=2
    volumes:
      - ./liquibase/changelog/:/liquibase/changelog/
    networks:
      - backend

#  ganache:
#    image: trufflesuite/ganache:latest
#    env_file: "./.env"
#    container_name: ganache
#    ports:
#      - "${ETHEREUM_PORT}:${ETHEREUM_PORT}"
#    networks:
#      - backend

networks:
  backend:
    driver: bridge
