### POST deploy by 1
POST http://localhost:8080/api/v1/users/1/groups/1/contract
Accept: application/json
Content-Type: application/json

{
    "credentials": {
        "private_key": "0xd8f15ecc9dbe5437ace1b0972f62170f79e52437dc2f0877108140e29141f606"
    },
    "contribute_eth_value": 20
}

####
#
## curl http://localhost:8545 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}'
#POST http://localhost:8545
#Content-Type: application/json
#
#{
#    "jsonrpc": "2.0",
#    "method": "eth_accounts",
#    "params": [],
#    "id": 1
#}
#
####
#POST http://localhost:8545
#Content-Type: application/json
#
#{
#    "jsonrpc": "2.0",
#    "method": "eth_getBalance",
#    "params": ["0x4ee77b7fb2e52864ab2db6c96ef7ae9065395c22", "latest"],
#    "id": 1
#}


