app:
  ethereum: http://${ETHEREUM_HOST}:${ETHEREUM_PORT}

server:
  port: ${SERVICE_PORT:8080}

spring:
  application:
    name: p2p-insurance
  jackson:
    time-zone: UTC
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
    change-log: classpath:../../../liquibase/changelog/changelog-main.yml

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

logging:
  config: classpath:log4j2-plain.xml
